# Generated by Django 4.2.2 on 2023-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_rate',
            field=models.IntegerField(default=0),
        ),
    ]
