# Generated by Django 4.2.2 on 2023-07-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_discount_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='brand_id',
        ),
    ]
