# Generated by Django 4.2.2 on 2023-07-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_discount_rate'),
        ('order', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='delivery_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.couponuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default='3000'),
        ),
        migrations.AddField(
            model_name='order',
            name='detail_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='discount_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
