# Generated by Django 4.2.2 on 2023-07-07 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('order', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='coupon_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='delivery_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default='3000'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='coupon_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.couponuser'),
        ),
    ]
