# Generated by Django 4.2.2 on 2023-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_price_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_subtype',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
