# Generated by Django 4.2.2 on 2023-08-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_content_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='delivery_fee',
            field=models.FloatField(default=3000),
        ),
    ]
