# Generated by Django 4.2.2 on 2023-08-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productoption_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='option_size',
            field=models.CharField(max_length=20),
        ),
    ]
